// ── Menu database ─────────────────────────────────────────────────────────────
export const RESTAURANTS = [
  { id: 'bellavista', name: 'Bellavista' },
  { id: 'marcos',     name: "Marco's Bistrot" },
]

export const MENU = [

  // ════════════════════════════════════════════════════════════════
  // BELLAVISTA
  // ════════════════════════════════════════════════════════════════

  { name: "[BV] Assaggiando Livigno (2 persone)",                              price: 37.00, category: "Antipasti & Starters",       restaurant: "bellavista" },
  { name: "[BV] Tagliere di Formaggi Misti",                                   price: 12.00, category: "Antipasti & Starters",       restaurant: "bellavista" },
  { name: "[BV] Bresaola della Valtellina",                                    price: 12.00, category: "Antipasti & Starters",       restaurant: "bellavista" },
  { name: "[BV] Bresaola al Carpaccio con Rucola, Porcini e Scaglie di Grana",price: 13.50, category: "Antipasti & Starters",       restaurant: "bellavista" },
  { name: "[BV] Sciatt Valtellinesi con Cicoria",                              price: 13.00, category: "Antipasti & Starters",       restaurant: "bellavista" },
  { name: "[BV] Prosciutto di Parma, Melone, Scaglie di Grana e Miele",       price: 15.00, category: "Antipasti & Starters",       restaurant: "bellavista" },
  { name: "[BV] Tartare di Manzo con Spuma di Ricotta e Tuorlo d'Uovo",       price: 16.00, category: "Antipasti & Starters",       restaurant: "bellavista" },

  { name: "[BV] Insalata Livigno",  price: 12.00, category: "Insalate", restaurant: "bellavista" },
  { name: "[BV] Insalata Caprese",  price: 10.00, category: "Insalate", restaurant: "bellavista" },
  { name: "[BV] Insalata Nizzarda", price: 12.00, category: "Insalate", restaurant: "bellavista" },
  { name: "[BV] Insalata di Pollo", price: 12.00, category: "Insalate", restaurant: "bellavista" },

  { name: "[BV] Sciolvar dal Livignasc", price: 21.00, category: "Pasta & Primi", restaurant: "bellavista" },

  { name: "[BV] Pizzoccheri Valtellinesi",               price: 14.00, category: "Pasta & Primi", restaurant: "bellavista" },
  { name: "[BV] Pizzoccheri Valtellinesi Senza Glutine",  price: 15.00, category: "Pasta & Primi", restaurant: "bellavista" },
  { name: "[BV] Pappardelle al Sugo di Cervo",           price: 14.00, category: "Pasta & Primi", restaurant: "bellavista" },
  { name: "[BV] Tagliatelle alla Boscaiola",             price: 13.00, category: "Pasta & Primi", restaurant: "bellavista" },
  { name: "[BV] Gnocchetti della Casa",                  price: 12.00, category: "Pasta & Primi", restaurant: "bellavista" },
  { name: "[BV] Tagliolini con Bitto e Pesteda",         price: 13.00, category: "Pasta & Primi", restaurant: "bellavista" },
  { name: "[BV] Lasagne all'Emiliana",                   price: 13.00, category: "Pasta & Primi", restaurant: "bellavista" },

  { name: "[BV] Spaghetti alla Carbonara",           price: 12.00, category: "Pasta & Primi", restaurant: "bellavista" },
  { name: "[BV] Spaghetti al Ragù",                  price: 12.00, category: "Pasta & Primi", restaurant: "bellavista" },
  { name: "[BV] Penne all'Arrabbiata",               price: 12.00, category: "Pasta & Primi", restaurant: "bellavista" },
  { name: "[BV] Risotto ai Funghi Porcini",           price: 14.00, category: "Pasta & Primi", restaurant: "bellavista" },
  { name: "[BV] Tortellini di Ricotta ai 4 Formaggi",price: 13.00, category: "Pasta & Primi", restaurant: "bellavista" },
  { name: "[BV] Tagliolini allo Scoglio",             price: 18.00, category: "Pasta & Primi", restaurant: "bellavista" },

  { name: "[BV] Minestrone del Contadino",        price: 10.00, category: "Zuppe", restaurant: "bellavista" },
  { name: "[BV] Minestra d'Orzo alla Grigionese", price: 10.00, category: "Zuppe", restaurant: "bellavista" },
  { name: "[BV] Crema di Porcini",                price: 12.00, category: "Zuppe", restaurant: "bellavista" },
  { name: "[BV] Zuppa di Gulasch",                price: 12.00, category: "Zuppe", restaurant: "bellavista" },

  { name: "[BV] Bastone della Casa",                         price: 20.00, category: "Secondi", restaurant: "bellavista" },
  { name: "[BV] Grigliata Mista di Carne",                   price: 22.00, category: "Secondi", restaurant: "bellavista" },
  { name: "[BV] Tagliata di Manzo con Rucola",               price: 24.00, category: "Secondi", restaurant: "bellavista" },
  { name: "[BV] Costata di Manzo Scottona ai Ferri 600gr",   price: 30.00, category: "Secondi", restaurant: "bellavista" },
  { name: "[BV] Filetto di Manzo alla Griglia",              price: 28.00, category: "Secondi", restaurant: "bellavista" },
  { name: "[BV] Filetto di Manzo al Pepe Verde",             price: 30.00, category: "Secondi", restaurant: "bellavista" },
  { name: "[BV] Chateaubriand con Salsa Bernese (min 2 pers)",price: 32.00, category: "Secondi", restaurant: "bellavista" },
  { name: "[BV] Scaloppina Panna e Funghi Porcini",          price: 17.00, category: "Secondi", restaurant: "bellavista" },
  { name: "[BV] Cotoletta alla Milanese",                    price: 16.00, category: "Secondi", restaurant: "bellavista" },
  { name: "[BV] Costoletta di Cervo al Timo e Cannella",     price: 30.00, category: "Secondi", restaurant: "bellavista" },

  { name: "[BV] Salmì di Cervo con Polenta",       price: 17.00, category: "Secondi", restaurant: "bellavista" },
  { name: "[BV] Funghi Porcini con Polenta",       price: 16.00, category: "Secondi", restaurant: "bellavista" },
  { name: "[BV] Salsiccetta Nostrana con Polenta", price: 14.00, category: "Secondi", restaurant: "bellavista" },
  { name: "[BV] Stinco di Maialino con Cotenna",   price: 21.00, category: "Secondi", restaurant: "bellavista" },

  { name: "[BV] Formaggio di Livigno",  price: 6.00,  category: "Contorni & Formaggi", restaurant: "bellavista" },
  { name: "[BV] Tagliere di Formaggi", price: 12.00, category: "Contorni & Formaggi", restaurant: "bellavista" },

  { name: "[BV] Patatine Fritte",          price: 4.00, category: "Contorni & Formaggi", restaurant: "bellavista" },
  { name: "[BV] Insalata Mista",           price: 5.00, category: "Contorni & Formaggi", restaurant: "bellavista" },
  { name: "[BV] Verdure alla Griglia",     price: 7.00, category: "Contorni & Formaggi", restaurant: "bellavista" },
  { name: "[BV] Verdure Cotte Miste",      price: 7.00, category: "Contorni & Formaggi", restaurant: "bellavista" },
  { name: "[BV] Spinaci al Burro",         price: 5.00, category: "Contorni & Formaggi", restaurant: "bellavista" },
  { name: "[BV] Funghi Porcini Trifolati", price: 5.00, category: "Contorni & Formaggi", restaurant: "bellavista" },
  { name: "[BV] Polenta",                  price: 7.00, category: "Contorni & Formaggi", restaurant: "bellavista" },
  { name: "[BV] Polenta Taragna",          price: 6.00, category: "Contorni & Formaggi", restaurant: "bellavista" },

  { name: "[BV] Pizza Bellavista", price: 16.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Emi",        price: 15.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Elda",       price: 14.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Livigno",    price: 14.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Laura",      price: 13.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Filippo",    price: 11.50, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Golosa",     price: 13.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Calzone Ciro",     price: 16.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Fit",        price: 13.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Happy",      price: 13.00, category: "Pizza", restaurant: "bellavista" },

  { name: "[BV] Pizza Margherita",        price: 7.50,  category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Prosciutto Cotto",  price: 9.00,  category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Salsiccia",         price: 9.00,  category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Funghi Champignon", price: 9.00,  category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Carciofi",          price: 9.00,  category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Capricciosa",       price: 11.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Diavola",           price: 10.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza ai Formaggi",       price: 10.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Tonno e Cipolla",   price: 10.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza alle Verdure",      price: 11.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Napoli",            price: 12.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Romana",            price: 9.00,  category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Funghi Porcini",    price: 10.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Wüstel",            price: 10.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Carbonara",         price: 12.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Zola e Noci",       price: 10.00, category: "Pizza", restaurant: "bellavista" },
  { name: "[BV] Pizza Pugliese",          price: 9.00,  category: "Pizza", restaurant: "bellavista" },

  { name: "[BV] Strudel di Mele Caldo con Gelato",            price: 6.50, category: "Dessert", restaurant: "bellavista" },
  { name: "[BV] Tiramisù Fatto in Casa",                      price: 5.50, category: "Dessert", restaurant: "bellavista" },
  { name: "[BV] Macedonia di Frutta Fresca",                  price: 5.50, category: "Dessert", restaurant: "bellavista" },
  { name: "[BV] Panna Cotta con Fragole/Cioccolato/Caramello",price: 7.00, category: "Dessert", restaurant: "bellavista" },
  { name: "[BV] Frutti di Bosco con Panna o Gelato",          price: 7.00, category: "Dessert", restaurant: "bellavista" },
  { name: "[BV] Torta Noci e Caramello",                      price: 6.50, category: "Dessert", restaurant: "bellavista" },
  { name: "[BV] Pizza alla Nutella",                          price: 8.00, category: "Dessert", restaurant: "bellavista" },
  { name: "[BV] Sorbetto Limone / Braulio / Grappa Mirtillo", price: 6.00, category: "Dessert", restaurant: "bellavista" },

  { name: "[BV] Acqua cl.75",                   price: 2.50,  category: "Birre", restaurant: "bellavista" },
  { name: "[BV] Bibite in Lattina cl.33",        price: 3.50,  category: "Birre", restaurant: "bellavista" },
  { name: "[BV] Succhi di Frutta",               price: 3.00,  category: "Birre", restaurant: "bellavista" },
  { name: "[BV] Birra in Bottiglia cl.33",       price: 3.50,  category: "Birre", restaurant: "bellavista" },
  { name: "[BV] Birra Analcolica cl.33",         price: 3.50,  category: "Birre", restaurant: "bellavista" },
  { name: "[BV] Birra alla Spina Piccola cl.20", price: 3.00,  category: "Birre", restaurant: "bellavista" },
  { name: "[BV] Birra alla Spina Media cl.40",   price: 5.00,  category: "Birre", restaurant: "bellavista" },
  { name: "[BV] Birra alla Spina Grande lt.1",   price: 11.50, category: "Birre", restaurant: "bellavista" },
  { name: "[BV] Birra Livigno 1816",             price: 6.50,  category: "Birre", restaurant: "bellavista" },

  { name: "[BV] Aperitivo della Casa Analcolico", price: 4.50, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Aperitivo della Casa Alcolico",   price: 4.50, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Crodino",                         price: 3.50, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Sanbittèr",                       price: 3.50, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Campari Soda",                    price: 3.50, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Bitter Campari",                  price: 3.50, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Campari & Bianco",                price: 5.00, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Sanbitter & Bianco",              price: 5.00, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Crodino & Bianco",                price: 5.00, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Pernod",                          price: 3.50, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Cynar",                           price: 3.50, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Martini Bianco/Rosso/Dry",        price: 3.50, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Aperol Spritz",                   price: 6.00, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Campari Orange",                  price: 6.00, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Bellini",                         price: 7.00, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Negroni",                         price: 7.00, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Americano",                       price: 7.00, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Rum & Cola",                      price: 7.00, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Whisky & Cola",                   price: 7.00, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Vodka Lemon",                     price: 7.00, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Gin Tonic",                       price: 7.00, category: "Aperitivi & Cocktail", restaurant: "bellavista" },
  { name: "[BV] Gin Lemon",                       price: 7.00, category: "Aperitivi & Cocktail", restaurant: "bellavista" },

  { name: "[BV] Braulio",             price: 3.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Braulio Riserva",     price: 4.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Taneda",              price: 3.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Genepì",              price: 3.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Averna",              price: 3.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Sambuca",             price: 3.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Baileys",             price: 4.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Grand Marnier",       price: 4.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Montenegro",          price: 3.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Ramazzotti",          price: 3.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Jägermeister",        price: 3.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Fernet Branca",       price: 3.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Fernet Menta",        price: 3.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Amaretto di Saronno", price: 3.00, category: "Spirits & Amari", restaurant: "bellavista" },

  { name: "[BV] Prosecco",                       price: 3.50, category: "Vini", restaurant: "bellavista" },
  { name: "[BV] Vino Bianco Italia",             price: 4.00, category: "Vini", restaurant: "bellavista" },
  { name: "[BV] Vino Rosso Valtellina",          price: 4.00, category: "Vini", restaurant: "bellavista" },
  { name: "[BV] Vino Rosso Valtellina Superiore",price: 6.50, category: "Vini", restaurant: "bellavista" },
  { name: "[BV] Vino Rosso Italia",              price: 4.00, category: "Vini", restaurant: "bellavista" },

  { name: "[BV] Jack Daniel's",  price: 5.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Jameson",        price: 5.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Glen Grant",     price: 5.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Johnnie Walker", price: 5.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] J&B",            price: 5.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Chivas Regal",   price: 6.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Laphroaig",      price: 6.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Glenlivet",      price: 6.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Glenfiddich",    price: 6.00, category: "Spirits & Amari", restaurant: "bellavista" },

  { name: "[BV] Grappa Gialla",          price: 4.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Grappa Moscato",         price: 5.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Grappa Barrique 18 Lune",price: 6.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Grappa Amarone",         price: 7.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Grappa Fieno",           price: 4.50, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Grappa Zirmol",          price: 4.50, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Grappa Mirtilli",        price: 4.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Grappa Frutta",          price: 3.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Williams",               price: 3.00, category: "Spirits & Amari", restaurant: "bellavista" },
  { name: "[BV] Grappa Miele",           price: 3.00, category: "Spirits & Amari", restaurant: "bellavista" },

  { name: "[BV] Espresso",                price: 1.20, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Espresso Doppio",         price: 2.20, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Espresso Corretto",       price: 1.40, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Espresso Decaffeinato",   price: 1.50, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Caffè Americano",         price: 1.70, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Caffè d'Orzo",            price: 1.70, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Caffè Ginseng",           price: 2.00, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Cappuccino",              price: 1.70, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Cappuccino Decaffeinato", price: 2.20, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Cappuccino Soia",         price: 2.50, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Cioccolata",              price: 4.00, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Cioccolata con Panna",    price: 4.50, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Latte Caldo",             price: 2.00, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Latte Macchiato",         price: 2.50, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] The Nero",                price: 2.00, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] The alla Frutta",         price: 2.00, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Tisane",                  price: 2.00, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Bombardino",              price: 5.00, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Lumumba",                 price: 5.00, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Irish Coffee",            price: 5.00, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Vin Brulé",               price: 5.00, category: "Caffè & Soft Drinks", restaurant: "bellavista" },
  { name: "[BV] Jägertee",                price: 5.00, category: "Caffè & Soft Drinks", restaurant: "bellavista" },

  { name: "[BV] Coperto", price: 2.50, category: "Coperto", restaurant: "bellavista" },


  // ════════════════════════════════════════════════════════════════
  // MARCO'S BISTROT
  // ════════════════════════════════════════════════════════════════

  { name: "[MP] Polpettine di Angus Fritte con Salsa Marcos (5pz)", price: 9.00,  category: "Antipasti & Starters", restaurant: "marcos" },
  { name: "[MP] Sciatt e Insalatina (6pz)",                         price: 8.00,  category: "Antipasti & Starters", restaurant: "marcos" },
  { name: "[MP] Il Tagliere del Marcos",                            price: 10.00, category: "Antipasti & Starters", restaurant: "marcos" },
  { name: "[MP] Formaggi Misti Locali",                             price: 10.00, category: "Antipasti & Starters", restaurant: "marcos" },
  { name: "[MP] Tartare di Angus Marcos Farm",                      price: 12.00, category: "Antipasti & Starters", restaurant: "marcos" },
  { name: "[MP] Bresaola di Livigno Carpacciata",                   price: 12.00, category: "Antipasti & Starters", restaurant: "marcos" },
  { name: "[MP] Cocotte di Moscardini in Umido",                    price: 11.00, category: "Antipasti & Starters", restaurant: "marcos" },
  { name: "[MP] Crudo San Daniele e Mozzarella Fiordilatte DOP",    price: 10.00, category: "Antipasti & Starters", restaurant: "marcos" },
  { name: "[MP] Angus Tonnato",                                     price: 12.00, category: "Antipasti & Starters", restaurant: "marcos" },
  { name: "[MP] Patatine Fritte",                                   price: 5.00,  category: "Antipasti & Starters", restaurant: "marcos" },
  { name: "[MP] Patate Saltate",                                    price: 6.00,  category: "Antipasti & Starters", restaurant: "marcos" },
  { name: "[MP] Avocado Toast",                                     price: 13.00, category: "Antipasti & Starters", restaurant: "marcos" },

  { name: "[MP] Tagliatelle con Zucca, Funghi e Salsiccia di Angus",   price: 13.50, category: "Pasta & Primi", restaurant: "marcos" },
  { name: "[MP] Ravioli con Ricotta di Ortica e Salsa di Edamame",      price: 13.50, category: "Pasta & Primi", restaurant: "marcos" },
  { name: "[MP] Raviolo con Carne di Angus, Salsa Brasata e Mirtilli",  price: 14.00, category: "Pasta & Primi", restaurant: "marcos" },
  { name: "[MP] Spaghettone Monograno Felicetti Carbonara o Ragù",      price: 12.50, category: "Pasta & Primi", restaurant: "marcos" },
  { name: "[MP] Gnocchi con Fonduta, Formaggi e Tartufo Scorzone",      price: 20.00, category: "Pasta & Primi", restaurant: "marcos" },
  { name: "[MP] Pizzoccheri con Verza, Burro di Malga e Formaggi",      price: 13.50, category: "Pasta & Primi", restaurant: "marcos" },
  { name: "[MP] Penne all'Arrabbiata",                                  price: 12.00, category: "Pasta & Primi", restaurant: "marcos" },
  { name: "[MP] Lasagne alla Bolognese",                                price: 12.00, category: "Pasta & Primi", restaurant: "marcos" },
  { name: "[MP] Tagliolino ai Funghi Porcini",                          price: 15.00, category: "Pasta & Primi", restaurant: "marcos" },

  { name: "[MP] Zuppa Goulash",         price: 12.00, category: "Zuppe", restaurant: "marcos" },
  { name: "[MP] Minestrone di Verdure", price: 9.00,  category: "Zuppe", restaurant: "marcos" },
  { name: "[MP] Trippa in Umido",       price: 12.00, category: "Zuppe", restaurant: "marcos" },
  { name: "[MP] Pasta e Fagioli",       price: 11.00, category: "Zuppe", restaurant: "marcos" },
  { name: "[MP] Passatelli in Brodo di Carne", price: 10.00, category: "Zuppe", restaurant: "marcos" },

  { name: "[MP] Costata Angus Marcos Farm (al hg)",                    price: 7.90,  category: "Secondi", restaurant: "marcos" },
  { name: "[MP] Cotoletta di Vitello alla Milanese + Patate Saltate",  price: 26.00, category: "Secondi", restaurant: "marcos" },
  { name: "[MP] Tagliata di Filetto di Manzo Vestita",                 price: 26.00, category: "Secondi", restaurant: "marcos" },
  { name: "[MP] Entrecote di Manzo 300g alla Griglia + Patate e Verdure", price: 25.00, category: "Secondi", restaurant: "marcos" },
  { name: "[MP] Costata di Manzo 500g + Patate Saltate e Verdure",     price: 27.00, category: "Secondi", restaurant: "marcos" },
  { name: "[MP] Petto di Tacchino alla Griglia + Verdure",             price: 16.00, category: "Secondi", restaurant: "marcos" },
  { name: "[MP] Salsiccia di Angus alla Griglia + Patate Saltate",     price: 16.00, category: "Secondi", restaurant: "marcos" },
  { name: "[MP] Trancio Salmone alla Griglia + Verdure e Tzatziki",    price: 23.00, category: "Secondi", restaurant: "marcos" },

  { name: "[MP] Caesar Salad con Straccetti di Angus",  price: 13.50, category: "Insalate", restaurant: "marcos" },
  { name: "[MP] Mediterranea",                          price: 12.50, category: "Insalate", restaurant: "marcos" },
  { name: "[MP] Nizzarda",                              price: 12.50, category: "Insalate", restaurant: "marcos" },
  { name: "[MP] Greca",                                 price: 12.50, category: "Insalate", restaurant: "marcos" },
  { name: "[MP] Caprese con Mozzarella Fior di Latte",  price: 13.00, category: "Insalate", restaurant: "marcos" },
  { name: "[MP] Insalata Mista",                        price: 5.50,  category: "Insalate", restaurant: "marcos" },
  { name: "[MP] Pomodori, Cipolle e Basilico",          price: 5.50,  category: "Insalate", restaurant: "marcos" },
  { name: "[MP] Verdure alla Griglia",                  price: 7.00,  category: "Insalate", restaurant: "marcos" },

  { name: "[MP] Marcos Smash Angus Burger & Chips", price: 16.00, category: "Burger & Sandwich", restaurant: "marcos" },
  { name: "[MP] Sarock Sandwich & Chips",           price: 14.00, category: "Burger & Sandwich", restaurant: "marcos" },
  { name: "[MP] Lùghegnia Burger & Chips",          price: 14.00, category: "Burger & Sandwich", restaurant: "marcos" },

  { name: "[MP] Torte Fatte in Casa",                   price: 5.00, category: "Dessert", restaurant: "marcos" },
  { name: "[MP] Tiramisù",                              price: 6.00, category: "Dessert", restaurant: "marcos" },
  { name: "[MP] Tortino al Cioccolato",                 price: 8.00, category: "Dessert", restaurant: "marcos" },
  { name: "[MP] Semifreddo all'Erba Iva",               price: 8.00, category: "Dessert", restaurant: "marcos" },
  { name: "[MP] Cheese Cake Scomposta",                 price: 8.00, category: "Dessert", restaurant: "marcos" },
  { name: "[MP] Sorbetto al Braulio",                   price: 5.00, category: "Dessert", restaurant: "marcos" },
  { name: "[MP] Affogato Caffè / Cioccolato / Amarena", price: 5.00, category: "Dessert", restaurant: "marcos" },
  { name: "[MP] Gelato",                                price: 2.00, category: "Dessert", restaurant: "marcos" },

  { name: "[MP] Pizza Italiana (tegamino)",  price: 13.00, category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza San Daniele (tegamino)",price: 16.00, category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza Mortazza (tegamino)",  price: 16.00, category: "Pizza", restaurant: "marcos" },

  { name: "[MP] Pizza Margherita",       price: 8.50,  category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza Napoli",           price: 9.50,  category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza Burrata D.O.P.",   price: 14.00, category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza Capricciosa",      price: 12.00, category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza 4 Formaggi",       price: 12.00, category: "Pizza", restaurant: "marcos" },

  { name: "[MP] Pizza Marinara",         price: 7.00,  category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza Lucifero",         price: 13.00, category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza Diavola",          price: 12.00, category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza Prosciutto e Funghi", price: 11.00, category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza Vegetariana",      price: 13.00, category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza Carbonara",        price: 12.00, category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza Livignasca",       price: 13.00, category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza Tonno e Cipolle",  price: 13.00, category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza 'Nduja",           price: 12.00, category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Calzone Farcito",        price: 12.00, category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza Marcos",           price: 13.00, category: "Pizza", restaurant: "marcos" },

  { name: "[MP] Pizza Gambero Bello",    price: 15.00, category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza Calabrese",        price: 12.00, category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Pizza Salmone",          price: 14.00, category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Garlic Pizza Bread",     price: 6.00,  category: "Pizza", restaurant: "marcos" },

  { name: "[MP] Puccia Caprese",         price: 8.00,  category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Puccia Livignasca",      price: 9.00,  category: "Pizza", restaurant: "marcos" },
  { name: "[MP] Puccia Golosa",          price: 8.00,  category: "Pizza", restaurant: "marcos" },

  // APERITIFS
  { name: "[MP] Franciacorta Brut Ronco Calino (Glas)",  price: 6.00, category: "Aperitivi & Cocktail", restaurant: "marcos" },
  { name: "[MP] Prosecco Biodinamico Organic",           price: 4.50, category: "Aperitivi & Cocktail", restaurant: "marcos" },
  { name: "[MP] Spritz / Aperol / Campari / Select / Hugo", price: 5.00, category: "Aperitivi & Cocktail", restaurant: "marcos" },
  { name: "[MP] Hugo Analcolico",                        price: 5.00, category: "Aperitivi & Cocktail", restaurant: "marcos" },
  { name: "[MP] Negroni / Americano / Sbagliato / Campari Shakerato", price: 6.00, category: "Aperitivi & Cocktail", restaurant: "marcos" },
  { name: "[MP] Gin Tonic / Mojito / Caipirinha",        price: 6.00, category: "Aperitivi & Cocktail", restaurant: "marcos" },
  { name: "[MP] Bloody Mary",                            price: 6.00, category: "Aperitivi & Cocktail", restaurant: "marcos" },
  { name: "[MP] Bloody Mary Special",                    price: 8.00, category: "Aperitivi & Cocktail", restaurant: "marcos" },
  { name: "[MP] Analcolici / Crodino / Campari Soda",    price: 3.50, category: "Aperitivi & Cocktail", restaurant: "marcos" },

  // DISTILLATI / LIQUORI / AMARI
  { name: "[MP] Whisky / Bourbon / Brandy / Cognac / Gin (piccolo)", price: 5.00, category: "Spirits & Amari", restaurant: "marcos" },
  { name: "[MP] Whisky / Bourbon / Brandy / Cognac / Gin (grande)",  price: 6.00, category: "Spirits & Amari", restaurant: "marcos" },
  { name: "[MP] Rum / Tequila / Wodka (piccolo)",         price: 5.00, category: "Spirits & Amari", restaurant: "marcos" },
  { name: "[MP] Rum / Tequila / Wodka (grande)",          price: 6.00, category: "Spirits & Amari", restaurant: "marcos" },
  { name: "[MP] Grappe / Distillati di Frutta (piccolo)", price: 4.00, category: "Spirits & Amari", restaurant: "marcos" },
  { name: "[MP] Grappe / Distillati di Frutta (grande)",  price: 5.00, category: "Spirits & Amari", restaurant: "marcos" },
  { name: "[MP] Liquori / Crème / Amari (piccolo)",       price: 3.00, category: "Spirits & Amari", restaurant: "marcos" },
  { name: "[MP] Liquori / Crème / Amari (grande)",        price: 4.00, category: "Spirits & Amari", restaurant: "marcos" },
  { name: "[MP] Shots / Ciupito",                         price: 3.00, category: "Spirits & Amari", restaurant: "marcos" },

  // BIRRE / BEERS / CIDER
  { name: "[MP] Schmucker Pils 0.25lt",                  price: 3.00, category: "Birre", restaurant: "marcos" },
  { name: "[MP] Schmucker Pils 0.4lt",                   price: 5.00, category: "Birre", restaurant: "marcos" },
  { name: "[MP] Mac Farland Red Ale 0.25lt",              price: 3.00, category: "Birre", restaurant: "marcos" },
  { name: "[MP] Mac Farland Red Ale 0.5lt",               price: 6.00, category: "Birre", restaurant: "marcos" },
  { name: "[MP] IPA Green Killer 0.25lt",                 price: 3.00, category: "Birre", restaurant: "marcos" },
  { name: "[MP] IPA Green Killer 0.5lt",                  price: 6.00, category: "Birre", restaurant: "marcos" },
  { name: "[MP] Murphys Irish Stout 0.25lt",              price: 3.00, category: "Birre", restaurant: "marcos" },
  { name: "[MP] Murphys Irish Stout 0.5lt",               price: 6.00, category: "Birre", restaurant: "marcos" },
  { name: "[MP] Best Beer Attraction 0.4lt",              price: 5.00, category: "Birre", restaurant: "marcos" },
  { name: "[MP] Paulaner Hefe Weizen 0.5lt (bottiglia)",  price: 5.00, category: "Birre", restaurant: "marcos" },
  { name: "[MP] Ichnusa Non Filtrata 0.33lt",             price: 3.50, category: "Birre", restaurant: "marcos" },
  { name: "[MP] Ichnusa Non Filtrata 0.5lt",              price: 6.00, category: "Birre", restaurant: "marcos" },
  { name: "[MP] Gluten Free Beer / Non Alcoholic 0.33lt", price: 3.50, category: "Birre", restaurant: "marcos" },
  { name: "[MP] Livigno 1816 Craft Local Beer 0.5lt",     price: 6.00, category: "Birre", restaurant: "marcos" },
  { name: "[MP] Bottle of Cider 0.56lt",                  price: 6.00, category: "Birre", restaurant: "marcos" },

  // VINI / WINES
  { name: "[MP] Rosso di Valtellina (bottiglia 0.75lt)",  price: 21.00, category: "Vini", restaurant: "marcos" },
  { name: "[MP] Rosso di Valtellina (bicchiere 0.12lt)",  price: 3.50,  category: "Vini", restaurant: "marcos" },
  { name: "[MP] Bianco di Valtellina (bottiglia 0.75lt)", price: 21.00, category: "Vini", restaurant: "marcos" },
  { name: "[MP] Bianco di Valtellina (bicchiere 0.12lt)", price: 3.50,  category: "Vini", restaurant: "marcos" },
  { name: "[MP] Franciacorta Brut Ronco Calino (bottiglia 0.75lt)", price: 33.00, category: "Vini", restaurant: "marcos" },
  { name: "[MP] Franciacorta Brut Ronco Calino (bicchiere 0.12lt)", price: 6.00,  category: "Vini", restaurant: "marcos" },

  // CAFFÈ / HOT DRINKS
  { name: "[MP] Espresso India",                   price: 1.20, category: "Caffè & Soft Drinks", restaurant: "marcos" },
  { name: "[MP] American Coffee Guatemala",         price: 2.00, category: "Caffè & Soft Drinks", restaurant: "marcos" },
  { name: "[MP] Cappuccino",                        price: 2.00, category: "Caffè & Soft Drinks", restaurant: "marcos" },
  { name: "[MP] Ovomaltina",                        price: 3.00, category: "Caffè & Soft Drinks", restaurant: "marcos" },
  { name: "[MP] Cioccolata con Panna",              price: 3.00, category: "Caffè & Soft Drinks", restaurant: "marcos" },
  { name: "[MP] The / Infusioni / Tisane",          price: 3.00, category: "Caffè & Soft Drinks", restaurant: "marcos" },
  { name: "[MP] Vin Brulé (Gluh Wine)",             price: 3.50, category: "Caffè & Soft Drinks", restaurant: "marcos" },
  { name: "[MP] Punch Arancio / Mandarino / Rum",   price: 3.50, category: "Caffè & Soft Drinks", restaurant: "marcos" },
  { name: "[MP] Bombardino / Lumumba",              price: 4.00, category: "Caffè & Soft Drinks", restaurant: "marcos" },
  { name: "[MP] Irish Coffee / Calipso Coffee",     price: 6.00, category: "Caffè & Soft Drinks", restaurant: "marcos" },
  { name: "[MP] Hot Whisky (sugar, lemon, cloves)", price: 5.00, category: "Caffè & Soft Drinks", restaurant: "marcos" },

  // BIBITE / SOFT DRINKS
  { name: "[MP] Acqua naturale / frizzante 0.75lt", price: 3.00, category: "Caffè & Soft Drinks", restaurant: "marcos" },
  { name: "[MP] Acqua naturale / frizzante 0.25lt", price: 1.50, category: "Caffè & Soft Drinks", restaurant: "marcos" },
  { name: "[MP] Bibite 0.33lt (Cola, Fanta, Sprite, Tonica, Lemonsoda, Ice Tea)", price: 3.00, category: "Caffè & Soft Drinks", restaurant: "marcos" },
  { name: "[MP] Spremuta / Squash Orange 0.35lt",   price: 4.00, category: "Caffè & Soft Drinks", restaurant: "marcos" },
  { name: "[MP] Succhi di Frutta Bio 0.25lt",        price: 3.00, category: "Caffè & Soft Drinks", restaurant: "marcos" },

  { name: "[MP] Coperto", price: 2.50, category: "Coperto", restaurant: "marcos" },
]

export const MENU_CATEGORIES = [...new Set(MENU.map(i => i.category))]
